import express from "express";
import multer from "multer";
import fs from "fs";
import { addFood, getCurrentOrders, getFoods, getOrderDetails, getVendorProfile, processOrder, updateCoverImage, updateVendorProfile, updateVendorService, VendorLogin } from "../controllers";
import { VendorTokenVerify } from "../middlewares";

const router = express.Router();

const imageStorage = multer.diskStorage({
    destination: function (req, file, callback) {
        const imagesDir = 'images'; // define the directory path
        // checking if the directory exists, if not, create it
        if (!fs.existsSync(imagesDir)) {
            fs.mkdirSync(imagesDir);
        }
        callback(null, imagesDir); // use the directory path
    },
    filename: function (req, file, callback) {
        callback(null, new Date().toISOString().replace(/:/g, '-') + '_' + file.originalname);
            // Note: I've replaced colons (:) in the timestamp generated by `toISOString()` with dashes (-). Colons are not allowed in filenames on some operating systems, so replacing them ensures compatibility.
    }
});

const images = multer({ storage: imageStorage }).array('images', 10);

router.post('/login', VendorLogin);
router.get('/profile', VendorTokenVerify, getVendorProfile);
router.patch('/profile', VendorTokenVerify, updateVendorProfile);
router.patch('/coverimage', VendorTokenVerify, images, updateCoverImage);
router.patch('/service', VendorTokenVerify, updateVendorService);

router.post('/food', VendorTokenVerify, images, addFood);
router.get('/foods', VendorTokenVerify, getFoods);

// handle orders from users
router.get('/orders', VendorTokenVerify, getCurrentOrders);
router.put('/order/:id/process', VendorTokenVerify, processOrder);
router.get('/order/:id', VendorTokenVerify, getOrderDetails);

export { router as VendorRoute };